version: '3.8'

services:
  builder:
    build: ./model_builder
    # SOLUTION TO DO 1 :
    volumes:
      - model_data:/shared_model

  api:
    build: ./api
    ports:
      - "8000:8000"
    # SOLUTION TO DO 2 :
    volumes:
      - model_data:/shared_model
      
    # SOLUTION TO DO 3 :
    depends_on:
      builder:
        # C'EST LE PIÈGE : Par défaut Docker utilise "service_started".
        # Ici, il faut absolument "service_completed_successfully".
        condition: "service_completed_successfully"

# SOLUTION TO DO 4 :
volumes:
  model_data: