# TO DO 1 : Partir de l'image officielle python 3.9-slim

# TO DO 2 : Définir /app comme dossier de travail

# TO DO 3 : On copie et installe les dépendances.
# On n'oublie pas --no-cache-dir pour éviter que pip conserve
# les fichiers téléchargés et alourdisse inutilement l’image Docker.

# TO DO 4 : Copier le script build_model.py dans le conteneur

# TO DO 5 : Lancer le script avec Python par défaut
CMD ["...", "..."]