# TO DO 1 : Partir de python 3.9-slim

WORKDIR /app

# TO DO 3 : On copie et installe les dépendances.
# On n'oublie pas --no-cache-dir pour éviter que pip conserve
# les fichiers téléchargés et alourdisse inutilement l’image Docker.


# TO DO 3 : Copier le main.py

# Lancement de l'API avec Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]